import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from "unocss";

export default defineConfig({
  shortcuts: [
    {
      "icon-btn":
        "p-2 aspect-square cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100",
      "absolute-fill":
        "p-2 aspect-square cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100",
    },
  ],
  rules: [
    [
      "display-none",
      {
        display: "none !important",
      },
    ],
  ],
  presets: [
    presetUno(),
    presetAttributify({
      strict: true,
    }),
    presetIcons({
      warn: true,
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: "DM Sans",
        serif: "DM Serif Display",
        mono: "DM Mono",
      },
    }),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
  safelist: [
    // Icons for framework.
    "i-carbon-checkmark-outline",
    "i-carbon-subtract-alt",
    "i-carbon-information",
    "i-carbon-warning",
    "i-carbon-arrow-up",
    "i-carbon-arrow-right",
    "i-carbon-arrow-down",
    "i-carbon-arrow-left",
    "i-ic-baseline-arrow-drop-down",
    "i-carbon-chevron-left",
    "i-carbon-chevron-right",
    "i-carbon-gradient",
    "i-carbon-settings-adjust",
    "i-carbon-color-palette",
    "i-carbon-restart",
    "i-carbon-chevron-up",
    "i-carbon-chevron-down",
    "i-carbon-circle-solid",
    "i-carbon-close-outline",
    "i-carbon-checkmark",
    "i-carbon-time",
    "i-carbon-calendar",
    "i-carbon-text-bold",
    "i-carbon-text-italic",
    "i-carbon-text-strikethrough",
    "i-carbon-text-underline",
    "i-carbon-list-bulleted",
    "i-carbon-list-numbered",
    "i-carbon-text-subscript",
    "i-carbon-text-superscript",
    "i-carbon-text-link",
    "i-carbon-fit-to-screen",
    "i-carbon-quotes",
    "i-carbon-text-align-left",
    "i-carbon-text-align-center",
    "i-carbon-text-align-right",
    "i-carbon-text-align-justify",
    "i-carbon-printer",
    "i-carbon-text-indent-less",
    "i-carbon-text-indent-more",
    "i-carbon-text-clear-format",
    "i-carbon-text-color",
    "i-carbon-text-font",
    "i-carbon-subtract",
    "i-carbon-undo",
    "i-carbon-redo",
    "i-ci-heading-h1",
    "i-ci-heading-h2",
    "i-ci-heading-h3",
    "i-ci-heading-h4",
    "i-ci-heading-h5",
    "i-ci-heading-h6",
    "i-carbon-code",
    "i-carbon-number-1",
    "i-carbon-number-2",
    "i-carbon-number-3",
    "i-carbon-number-4",
    "i-carbon-number-5",
    "i-carbon-number-6",
    "i-carbon-number-7",
    "i-carbon-caret-down",
    "i-carbon-add",
    "i-carbon-close",
    "i-carbon-close-filled",
    "i-carbon-error-filled",
    "i-carbon-page-first",
    "i-carbon-star-filled",
    "i-carbon-edit",
    "i-carbon-error",
    "i-carbon-warning-alt-filled",
    "i-carbon-play-filled-alt",
    "i-carbon-add-filled",
    "i-carbon-cloud-upload",
    "i-carbon-sort-remove",
    "i-carbon-task-remove",

    // Other Icons
    "i-carbon-analytics",
    "i-carbon-download",
    "i-carbon-upload",
    "i-carbon-user-avatar-filled",
    "i-clarity-flask-solid",
    "i-emojione-crescent-moon",
    "i-emojione-flag-for-united-states",
    "i-emojione-flag-for-united-kingdom",
    "i-emojione-sun",
    "i-fa6-solid-gears",
  ],
});
