export enum Biome {
  AbyssCliffs = "Abyss Cliffs",
  BlueCrater = "Blue Crater",
  CraterLake = "Crater Lake",
  DangleSpires = "Dangle Spires",
  DesertCanyons = "Desert Canyons",
  DuneDesert = "Dune Desert",
  EasternDuneForest = "Eastern Dune Forest",
  GrassFields = "Grass Fields",
  Islands = "Islands",
  LakeForest = "Lake Forest",
  MazeCanyon = "Maze Canyon",
  NorthernForest = "Northern Forest",
  ParadiseIsland = "Paradise Island",
  RedBambooFields = "Red Bamboo Fields",
  RedJungle = "Red Jungle",
  RockyDesert = "Rocky Desert",
  SnaketreeForest = "Snaketree Forest",
  SouthernForest = "Southern Forest",
  SpireCoast = "Spire Coast",
  Swamp = "Swamp",
  TitanForest = "Titan Forest",
  WesternDuneForest = "Western Dune Forest",
}

export const gameMapBiomes: Record<
  number,
  Record<number, Biome | undefined>
> = {
  1: {
    1: Biome.ParadiseIsland,
    2: Biome.ParadiseIsland,
    4: Biome.GrassFields,
    5: Biome.GrassFields,
    6: Biome.GrassFields,
    8: Biome.BlueCrater,
    9: Biome.BlueCrater,
  },
  2: {
    3: Biome.GrassFields,
    4: Biome.GrassFields,
    5: Biome.GrassFields,
    6: Biome.SouthernForest,
    7: Biome.SouthernForest,
    8: Biome.BlueCrater,
    9: Biome.BlueCrater,
    10: Biome.AbyssCliffs,
  },
  3: {
    2: Biome.DangleSpires,
    3: Biome.DangleSpires,
    4: Biome.SnaketreeForest,
    5: Biome.SnaketreeForest,
    6: Biome.GrassFields,
    7: Biome.SouthernForest,
    8: Biome.BlueCrater,
    9: Biome.BlueCrater,
    10: Biome.AbyssCliffs,
  },
  4: {
    1: Biome.Islands,
    2: Biome.DangleSpires,
    3: Biome.DangleSpires,
    4: Biome.WesternDuneForest,
    5: Biome.WesternDuneForest,
    6: Biome.EasternDuneForest,
    7: Biome.EasternDuneForest,
    8: Biome.EasternDuneForest,
    9: Biome.EasternDuneForest,
    10: Biome.AbyssCliffs,
  },
  5: {
    1: Biome.Islands,
    2: Biome.DangleSpires,
    3: Biome.WesternDuneForest,
    4: Biome.RedJungle,
    5: Biome.RedBambooFields,
    6: Biome.RedBambooFields,
    7: Biome.EasternDuneForest,
    8: Biome.TitanForest,
    9: Biome.EasternDuneForest,
    10: Biome.Swamp,
    11: Biome.Swamp,
  },
  6: {
    1: Biome.RedJungle,
    2: Biome.RedJungle,
    3: Biome.RedJungle,
    4: Biome.RedJungle,
    5: Biome.RedBambooFields,
    6: Biome.RedBambooFields,
    7: Biome.TitanForest,
    8: Biome.TitanForest,
    9: Biome.TitanForest,
    10: Biome.Swamp,
    11: Biome.Swamp,
  },
  7: {
    0: Biome.RockyDesert,
    1: Biome.RockyDesert,
    2: Biome.RockyDesert,
    3: Biome.RockyDesert,
    4: Biome.CraterLake,
    5: Biome.CraterLake,
    6: Biome.LakeForest,
    7: Biome.LakeForest,
    8: Biome.MazeCanyon,
    9: Biome.TitanForest,
    10: Biome.TitanForest,
    11: Biome.TitanForest,
    12: Biome.Swamp,
    13: Biome.DuneDesert,
  },
  8: {
    0: Biome.RockyDesert,
    1: Biome.RockyDesert,
    2: Biome.RockyDesert,
    3: Biome.RockyDesert,
    4: Biome.CraterLake,
    5: Biome.CraterLake,
    6: Biome.NorthernForest,
    7: Biome.NorthernForest,
    8: Biome.MazeCanyon,
    9: Biome.DesertCanyons,
    10: Biome.DuneDesert,
    11: Biome.DuneDesert,
    12: Biome.DuneDesert,
    13: Biome.DuneDesert,
  },
  9: {
    0: Biome.RockyDesert,
    1: Biome.RockyDesert,
    2: Biome.RockyDesert,
    3: Biome.RockyDesert,
    4: Biome.RockyDesert,
    5: Biome.NorthernForest,
    6: Biome.NorthernForest,
    7: Biome.NorthernForest,
    8: Biome.DesertCanyons,
    9: Biome.DesertCanyons,
    10: Biome.DuneDesert,
    11: Biome.DuneDesert,
    12: Biome.DuneDesert,
    13: Biome.DuneDesert,
  },
  10: {
    0: Biome.RockyDesert,
    1: Biome.RockyDesert,
    2: Biome.RockyDesert,
    3: Biome.RockyDesert,
    4: Biome.RockyDesert,
    5: Biome.DesertCanyons,
    6: Biome.SpireCoast,
    7: Biome.SpireCoast,
    8: Biome.SpireCoast,
    9: Biome.SpireCoast,
    10: Biome.SpireCoast,
    11: Biome.DuneDesert,
    12: Biome.DuneDesert,
    13: Biome.DuneDesert,
  },
  11: {
    8: Biome.SpireCoast,
    9: Biome.SpireCoast,
    10: Biome.SpireCoast,
    11: Biome.DuneDesert,
    12: Biome.DuneDesert,
    13: Biome.DuneDesert,
  },
  12: {
    9: Biome.SpireCoast,
    10: Biome.SpireCoast,
    11: Biome.DuneDesert,
    12: Biome.DuneDesert,
    13: Biome.DuneDesert,
  },
};
